<script lang="ts">
  import type { PageData } from './$types';
  import { 
    FolderGit2, 
    Layers, 
    Search, 
    Tag, 
    ArrowRight, 
    AlertTriangle, 
    FileCode2, 
    Sparkles, 
    FolderPlus 
  } from 'lucide-svelte';
  import TagBadge from '$lib/components/TagBadge.svelte';
  import RegisterModal from '$lib/components/RegisterModal.svelte';

  let { data }: { data: PageData } = $props();

  let searchQuery = $state('');
  let selectedTag = $state('');
  let registerModalOpen = $state(false);

  // Filter projects by search query and selected tag
  let filteredProjects = $derived(
    data.projects.filter(p => {
      const q = searchQuery.toLowerCase().trim();
      const matchesSearch = 
        !q ||
        p.name.toLowerCase().includes(q) ||
        p.path.toLowerCase().includes(q) ||
        (p.description && p.description.toLowerCase().includes(q)) ||
        p.tags.some(t => t.toLowerCase().includes(q));

      const matchesTag = !selectedTag || p.tags.includes(selectedTag);

      return matchesSearch && matchesTag;
    })
  );

  function toggleTag(tag: string) {
    if (selectedTag === tag) {
      selectedTag = '';
    } else {
      selectedTag = tag;
    }
  }

  function formatDate(isoStr?: string) {
    if (!isoStr) return 'Recently';
    try {
      const d = new Date(isoStr);
      return d.toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' });
    } catch {
      return isoStr;
    }
  }
</script>

<div class="page-container">
  <!-- Hero / Summary Banner -->
  <section class="hero-section">
    <div class="hero-content">
      <div class="hero-badge">
        <Sparkles size={14} />
        <span>Central Knowledge & Topology Hub</span>
      </div>
      <h1>Interactive Artifacts Manager</h1>
      <p class="hero-desc">
        Explore architectures, database topologies, refactor breakdowns, and system design artifacts generated by AI agents across all workspace projects.
      </p>
    </div>

    <!-- Quick Stats Cards -->
    <div class="stats-grid">
      <div class="stat-card glass-panel">
        <div class="stat-icon icon-indigo">
          <FolderGit2 size={20} />
        </div>
        <div class="stat-info">
          <span class="stat-value">{data.stats.totalProjects}</span>
          <span class="stat-label">Registered Projects</span>
        </div>
      </div>

      <div class="stat-card glass-panel">
        <div class="stat-icon icon-cyan">
          <Layers size={20} />
        </div>
        <div class="stat-info">
          <span class="stat-value">{data.stats.totalArtifacts}</span>
          <span class="stat-label">Total Artifacts</span>
        </div>
      </div>

      <div class="stat-card glass-panel">
        <div class="stat-icon icon-emerald">
          <Tag size={20} />
        </div>
        <div class="stat-info">
          <span class="stat-value">{data.stats.totalTags}</span>
          <span class="stat-label">Discovered Tags</span>
        </div>
      </div>
    </div>
  </section>

  <!-- Controls Bar -->
  <section class="controls-section glass-panel">
    <div class="search-wrap">
      <Search size={18} class="search-icon" />
      <input 
        type="text" 
        class="input-glass search-input" 
        placeholder="Search projects, tags, or paths..." 
        bind:value={searchQuery}
      />
      {#if searchQuery}
        <button class="clear-btn" onclick={() => (searchQuery = '')}>×</button>
      {/if}
    </div>

    {#if data.allTags.length > 0}
      <div class="tags-scroller">
        <span class="tags-label">Tags:</span>
        <button 
          type="button" 
          class="tag-pill" 
          class:active={selectedTag === ''} 
          onclick={() => (selectedTag = '')}
        >
          All
        </button>
        {#each data.allTags as tag}
          <TagBadge 
            {tag} 
            active={selectedTag === tag} 
            onclick={toggleTag} 
          />
        {/each}
      </div>
    {/if}
  </section>

  <!-- Projects Grid -->
  <section class="projects-section">
    <div class="section-header">
      <h2>Projects ({filteredProjects.length})</h2>
      {#if selectedTag || searchQuery}
        <button class="reset-filter-btn" onclick={() => { selectedTag = ''; searchQuery = ''; }}>
          Reset filters
        </button>
      {/if}
    </div>

    {#if filteredProjects.length === 0}
      <div class="empty-state glass-panel">
        <div class="empty-icon">
          <FolderPlus size={36} class="text-indigo-400" />
        </div>
        <h3>No projects matched</h3>
        <p class="empty-text">
          {#if searchQuery || selectedTag}
            No projects match the current search or tag filter.
          {:else}
            No projects registered yet in <code>~/.artifacts-manager.json</code>.
          {/if}
        </p>
        <button class="btn-primary" onclick={() => (registerModalOpen = true)}>
          <FolderPlus size={16} />
          <span>Register a Project</span>
        </button>
      </div>
    {:else}
      <div class="projects-grid">
        {#each filteredProjects as project}
          <a href="/project/{project.slug}" class="project-card glass-panel">
            <div class="card-header">
              <div class="project-icon-box">
                <FolderGit2 size={20} class="text-indigo-400" />
              </div>
              <div class="project-title-box">
                <h3>{project.name}</h3>
                <span class="project-path" title={project.path}>{project.path}</span>
              </div>
            </div>

            {#if project.description}
              <p class="project-desc">{project.description}</p>
            {/if}

            {#if !project.exists}
              <div class="status-warning">
                <AlertTriangle size={14} />
                <span>Directory not found on disk</span>
              </div>
            {/if}

            <div class="card-footer">
              <div class="artifacts-count-badge">
                <FileCode2 size={14} />
                <span>
                  {project.activeArtifactCount ?? project.artifactCount} {((project.activeArtifactCount ?? project.artifactCount) === 1) ? 'artifact' : 'artifacts'}
                  {#if project.archivedArtifactCount && project.archivedArtifactCount > 0}
                    <span class="archived-text">({project.archivedArtifactCount} archived)</span>
                  {/if}
                </span>
              </div>

              {#if project.tags.length > 0}
                <div class="project-tags">
                  {#each project.tags.slice(0, 3) as tag}
                    <span class="mini-tag">#{tag}</span>
                  {/each}
                  {#if project.tags.length > 3}
                    <span class="mini-tag-more">+{project.tags.length - 3}</span>
                  {/if}
                </div>
              {/if}

              <div class="card-arrow">
                <ArrowRight size={16} />
              </div>
            </div>
          </a>
        {/each}
      </div>
    {/if}
  </section>
</div>

<RegisterModal bind:open={registerModalOpen} onRegistered={() => {
  if (typeof window !== 'undefined') window.location.reload();
}} />

<style>
  .page-container {
    display: flex;
    flex-direction: column;
    gap: 2rem;
  }

  .hero-section {
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
  }

  .hero-content {
    max-width: 800px;
  }

  .hero-badge {
    display: inline-flex;
    align-items: center;
    gap: 0.4rem;
    padding: 0.3rem 0.75rem;
    border-radius: var(--radius-full);
    background: var(--accent-indigo-subtle);
    border: 1px solid rgba(99, 102, 241, 0.3);
    color: #a5b4fc;
    font-size: 0.775rem;
    font-weight: 600;
    margin-bottom: 0.75rem;
  }

  .hero-content h1 {
    font-size: 2.35rem;
    margin-bottom: 0.5rem;
    background: linear-gradient(135deg, #ffffff 0%, #cbd5e1 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
  }

  .hero-desc {
    font-size: 1.05rem;
    color: var(--text-secondary);
    line-height: 1.6;
  }

  .stats-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
    gap: 1.25rem;
  }

  .stat-card {
    padding: 1.25rem;
    display: flex;
    align-items: center;
    gap: 1rem;
  }

  .stat-icon {
    width: 44px;
    height: 44px;
    border-radius: var(--radius-md);
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .icon-indigo {
    background: var(--accent-indigo-subtle);
    color: var(--accent-indigo);
    border: 1px solid rgba(99, 102, 241, 0.3);
  }

  .icon-cyan {
    background: var(--accent-cyan-subtle);
    color: var(--accent-cyan);
    border: 1px solid rgba(6, 182, 212, 0.3);
  }

  .icon-emerald {
    background: var(--accent-emerald-subtle);
    color: var(--accent-emerald);
    border: 1px solid rgba(16, 185, 129, 0.3);
  }

  .stat-info {
    display: flex;
    flex-direction: column;
  }

  .stat-value {
    font-family: var(--font-heading);
    font-size: 1.65rem;
    font-weight: 700;
    color: var(--text-primary);
    line-height: 1.2;
  }

  .stat-label {
    font-size: 0.8rem;
    color: var(--text-muted);
    font-weight: 500;
  }

  /* Controls */
  .controls-section {
    padding: 1.25rem;
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }

  .search-wrap {
    position: relative;
    display: flex;
    align-items: center;
    width: 100%;
  }

  :global(.search-icon) {
    position: absolute;
    left: 1rem;
    color: var(--text-muted);
    pointer-events: none;
  }

  .search-input {
    width: 100%;
    padding-left: 2.75rem;
    padding-right: 2.5rem;
  }

  .clear-btn {
    position: absolute;
    right: 0.85rem;
    font-size: 1.2rem;
    color: var(--text-muted);
  }

  .clear-btn:hover {
    color: var(--text-primary);
  }

  .tags-scroller {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    flex-wrap: wrap;
  }

  .tags-label {
    font-size: 0.8rem;
    color: var(--text-muted);
    font-weight: 600;
    margin-right: 0.25rem;
  }

  /* Projects Section */
  .projects-section {
    display: flex;
    flex-direction: column;
    gap: 1.25rem;
  }

  .section-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
  }

  .section-header h2 {
    font-size: 1.35rem;
  }

  .reset-filter-btn {
    font-size: 0.8rem;
    color: var(--accent-indigo);
    text-decoration: underline;
  }

  .projects-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(340px, 1fr));
    gap: 1.25rem;
  }

  .project-card {
    padding: 1.35rem;
    display: flex;
    flex-direction: column;
    gap: 1rem;
    position: relative;
  }

  .project-card:hover {
    transform: translateY(-2px);
    border-color: rgba(99, 102, 241, 0.4);
    box-shadow: var(--shadow-lg), 0 0 20px -3px rgba(99, 102, 241, 0.2);
  }

  .card-header {
    display: flex;
    align-items: flex-start;
    gap: 0.85rem;
  }

  .project-icon-box {
    width: 40px;
    height: 40px;
    border-radius: var(--radius-md);
    background: rgba(99, 102, 241, 0.12);
    border: 1px solid rgba(99, 102, 241, 0.25);
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
  }

  .project-title-box {
    display: flex;
    flex-direction: column;
    min-width: 0;
  }

  .project-title-box h3 {
    font-size: 1.1rem;
    color: var(--text-primary);
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  .project-path {
    font-family: var(--font-mono);
    font-size: 0.725rem;
    color: var(--text-muted);
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  .project-desc {
    font-size: 0.85rem;
    color: var(--text-secondary);
    line-height: 1.5;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
    overflow: hidden;
  }

  .status-warning {
    display: flex;
    align-items: center;
    gap: 0.4rem;
    font-size: 0.75rem;
    color: var(--accent-amber);
    background: var(--accent-amber-subtle);
    padding: 0.35rem 0.65rem;
    border-radius: var(--radius-sm);
    border: 1px solid rgba(245, 158, 11, 0.3);
  }

  .card-footer {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding-top: 0.75rem;
    border-top: 1px solid var(--border-subtle);
    margin-top: auto;
  }

  .artifacts-count-badge {
    display: flex;
    align-items: center;
    gap: 0.35rem;
    font-size: 0.775rem;
    font-weight: 600;
    color: var(--accent-indigo);
  }

  .archived-text {
    color: #fbbf24;
    font-size: 0.725rem;
    font-weight: 500;
    margin-left: 0.25rem;
  }

  .project-tags {
    display: flex;
    gap: 0.35rem;
    overflow: hidden;
  }

  .mini-tag {
    font-size: 0.7rem;
    color: var(--text-muted);
    background: rgba(255, 255, 255, 0.04);
    padding: 0.15rem 0.4rem;
    border-radius: var(--radius-sm);
  }

  .mini-tag-more {
    font-size: 0.7rem;
    color: var(--accent-cyan);
  }

  .card-arrow {
    color: var(--text-muted);
    transition: transform 0.15s ease;
  }

  .project-card:hover .card-arrow {
    transform: translateX(3px);
    color: var(--text-primary);
  }

  .empty-state {
    padding: 3.5rem 2rem;
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
    gap: 1rem;
  }

  .empty-icon {
    width: 64px;
    height: 64px;
    border-radius: var(--radius-lg);
    background: var(--accent-indigo-subtle);
    border: 1px solid rgba(99, 102, 241, 0.3);
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .empty-text {
    font-size: 0.9rem;
    color: var(--text-secondary);
    max-width: 420px;
  }
</style>
